// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
  PHOTOS_BUCKET: R2Bucket;
  PHOTO_CACHE: KVNamespace;
  THUMBNAIL_WIDTH: string;
  THUMBNAIL_HEIGHT: string;
  THUMBNAIL_QUALITY: string;
  ORIGINAL_QUALITY: string;
}

type CfProperties<T = unknown> = {
  cf: {
    tlsVersion: string;
    tlsCipher: string;
    country: string;
    colo: string;
  } & T;
};
